name: mask_text_input_formatter_example
description: Mask Text Input Formatter Example
version: 1.0.0
publish_to: none
homepage: https://github.com/siqwin/mask_text_input_formatter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter:
    path: ../

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter