name: mask_text_input_formatter
description: The package provides TextInputFormatter for TextField and TextFormField which format the input by a given mask.
version: 2.7.0
homepage: https://github.com/siqwin/mask_text_input_formatter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter